[package]
name = "render-3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.20.2", features = ["serde"] }
image = "0.24.0"
serde = "1.0.136"
serde_yaml = "0.8.23"
